import json
import os

source_path = '/Users/waylonhuang/.gemini/tmp/epub/work_morisaki/OEBPS/Text/part0001.xhtml.sentences.json'
dest_path = '/Users/waylonhuang/.gemini/tmp/epub/work_morisaki/OEBPS/Text/part0001.xhtml.translations.2.json'

with open(source_path, 'r', encoding='utf-8') as f:
    sentences = json.load(f)

# Slice 600 to 900 (inclusive)
target_sentences = sentences[600:901]

# I will provide the translations here. 
# Since I am an AI, I will generate them in the script to ensure they are complete and formatted correctly.
translations = {
    "そう思うと、彼がちょっとうらやましかった。": "Thinking about it that way, I felt a little envious of him.",
    "<br/>\r\n  「まあ、そんな感じに二十代はずっとぷらぷらしてたからねえ。": "<br/>\r\n  \"Well, I just drifted through my twenties like that.",
    "親父にはしょっちゅう怒られてたもんだよ。": "My father was always scolding me for it.",
    "そうこうしているうちに親父も倒れて死んじゃって、そのまま僕がこの店を継ぐことになったんだ」<br/>\r\n  「後悔してたりする？」": "Then, before I knew it, my father collapsed and passed away, and I ended up taking over the shop just like that.\"<br/>\r\n  \"Do you ever regret it?\"",
    "<br/>\r\n  「まさか」と叔父は笑って言った。": "<br/>\r\n  \"Not at all,\" my uncle said with a laugh.",
    "「これほど僕に向いてる職業もないよ。": "\"There's no other job that suits me better than this.",
    "本が好きな人間にとって、この街ほど素晴らしい環境は二つとないからね。": "For someone who loves books, there's no better place in the world than this neighborhood.",
    "ここで店をやれることを、僕は誇りに思っている。": "I'm proud to be able to run a shop here.",
    "だから、親父やじいさんには感謝してもしたりないくらいだね」<br/>\r\n  「ふうん。": "So, I really can't thank my father and grandfather enough.\"<br/>\r\n  \"Hmm.",
    "なんかいいなあ、叔父さんは」<br/>\r\n  「何がだい？」": "Must be nice, Uncle.\"<br/>\r\n  \"What is?\"",
    "<br/>\r\n  　叔父はきょとんとした顔をする。": "<br/>\r\n  My uncle gave me a blank look.",
    "<br/>\r\n  「だって自分の好きなことやって、それで生きていけるんだもん」<br/>\r\n  「そうでもないよ。": "<br/>\r\n  \"I mean, you're doing what you love and making a living out of it.\"<br/>\r\n  \"It's not quite that simple.",
    "僕なりに最初はかなり抵抗があったんだよ。": "I actually resisted a lot at first.",
    "何せ自分が親父のあとを継ぐなんて、若いころは夢にも思わなかったからね。": "After all, I never dreamed of following in my father's footsteps when I was young.",
    "いまだって迷うことばかりだよ。": "Even now, I'm full of doubts.",
    "でもまあ、自分が本当に何を求めているかなんて、すぐにわかることじゃないのかもしれない。": "But then again, maybe what you really want isn't something you can figure out right away.",
    "一生をかけて少しずつわかっていくものなのかもしれないよ」<br/>\r\n  「わたし……、こんな風に何もしないで、時間を無駄にしてるかな……」<br/>\r\n  　叔父は、わたしを見つめてやさしく微笑んだ。": "Perhaps it's something you understand bit by bit over a lifetime.\"<br/>\r\n  \"I wonder... am I just wasting my time like this, doing nothing?\"<br/>\r\n  My uncle looked at me and smiled gently.",
    "<br/>\r\n  「そんなことないと思うよ。": "<br/>\r\n  \"I don't think so.",
    "ときには人生、立ち止まってみることも大切だよ。": "Sometimes it's important to just stop and stay still for a while.",
    "これはまあ、人生という長い旅における一休みさ。": "Think of it as a rest in the long journey of life.",
    "ここは波止場であり、君という船は、しばらくここで<ruby><rb>錨</rb><rt>いかり</rt></ruby>をおろしているってだけだよ。": "This is a harbor, and your ship is simply anchored here for a bit.",
    "で、よく休んだら、また船出をすればいい」<br/>\r\n  「そんなこと言うくせに、わたしが寝てると文句言うんですね」とわたしは憎々しげに言った。": "Once you've had a good rest, you can set sail again.\"<br/>\r\n  \"You say that, but you still complain when I'm sleeping,\" I said, half-joking.",
    "<br/>\r\n  　叔父さんは、あははと声を出して笑った。": "<br/>\r\n  My uncle laughed out loud.",
    "「人間とは、矛盾だらけの生き物なのさ」<br/>\r\n  　わたしも思わず、ぷっと吹き出した。": "\"Humans are creatures full of contradictions, after all.\"<br/>\r\n  I couldn't help but burst into a little laugh too.",
    "まったくこれだもんなあ、この人は。": "That's just how he is, I thought.",
    "<br/>\r\n  「それで叔父さんは、旅をしたり、本を読んだりして、いろんなことを学んだ？」": "<br/>\r\n  \"So, did you learn a lot of things by traveling and reading books, Uncle?\"",
    "<br/>\r\n  「そうだねえ。": "<br/>\r\n  \"Well, let's see.",
    "でも、どこに行っても、どれだけ本を読んでも、自分はまだ何も知らない、何ひとつ見てないんじゃないかって気にもなったよ。": "But no matter where I went or how many books I read, I often felt like I still didn't know anything, like I hadn't seen a single thing.",
    "それが人生というものさ。": "That's just what life is.",
    "いつだって迷いながら生きていくんだ。": "We've always lived while being lost.",
    "山頭火の歌にもあるだろう？": "There's a poem by Santoka, isn't there?",
    "『分け入っても分け入っても青い山』ってやつがさ」<br/>\r\n  「ねえ、叔父さん」<br/>\r\n  　わたしはずっと訊いてみたかったことを、この場の勢いを借りて口にしてみようと思った。": "'Going deeper and deeper, yet still the green mountains.'\"<br/>\r\n  \"Hey, Uncle.\"<br/>\r\n  I decided to seize the moment and ask the question that had been on my mind for a long time.",
    "<br/>\r\n  「うん？」": "<br/>\r\n  \"Yeah?\"",
    "<br/>\r\n  「桃子おばさんはなんで出ていっちゃったの？」": "<br/>\r\n  \"Why did Aunt Momoko leave?\"",
    "<br/>\r\n  「うーん。": "<br/>\r\n  \"Hmm.",
    "僕と彼女は、考え方がもともと似ていてね。": "She and I were very similar in the way we thought.",
    "それが僕らを結び付けたし、それが僕らを分かつ原因にもなったんだと思う。": "I think that's what brought us together, and also what eventually drove us apart.",
    "僕らはまさに旅の途上で出会って、恋に落ちたんだ。": "We truly met and fell in love while we were both on a journey.",
    "でも、いつまでも同じ旅を続けられるわけじゃない。": "But you can't stay on the same journey forever.",
    "いつかはどこかの港に<ruby><rb>辿</rb><rt>たど</rt></ruby>りつかなきゃいけない。": "Eventually, you have to reach a harbor somewhere.",
    "二人の終着点が一緒だと僕は思っていたけど、残念ながらそうはならなかった」<br/>\r\n  「そうなんだ……。": "I thought our final destinations were the same, but unfortunately, they weren't.\"<br/>\r\n  \"I see...",
    "そのときはどんな気持ちだった？": "How did you feel back then?",
    "悲しかった？」": "Were you sad?\"",
    "<br/>\r\n  「そうだなあ……」と叔父は、分厚い雲に覆われた空を見上げて言った。": "<br/>\r\n  \"Well...\" my uncle said, looking up at the sky covered in thick clouds.",
    "「悲しいというのももちろんあったよ。": "\"Of course I was sad.",
    "でも……」<br/>\r\n  「でも……？」": "But...\"<br/>\r\n  \"But...?\"",
    "<br/>\r\n  「でも、いまは、彼女がいまどこで何をしていようと、やっぱり幸せでいてほしいと願ってる」<br/>\r\n  「だって」とわたしは彼の気持ちがつかみきれなくて言った。": "<br/>\r\n  \"But now, wherever she is and whatever she's doing, I just want her to be happy.\"<br/>\r\n  \"But,\" I said, not quite understanding his feelings.",
    "「おばさんは、叔父さんを捨てて出て行っちゃったんだよ？」": "\"Aunt Momoko left you behind, didn't she?\"",
    "<br/>\r\n  「でも桃子は、僕が本気で愛したただ一人の女性なんだ。": "<br/>\r\n  \"But Momoko is the only woman I ever truly loved.",
    "その事実は一生変わりはしない。": "That fact will never change for the rest of my life.",
    "二人で過ごした思い出は、いまでも僕の胸にしっかり残っている。": "The memories we shared are still tucked away safely in my heart.",
    "そういう意味では、僕はまだ桃子を愛しているんだ」<br/>\r\n  　どうしてそんな風に思えるの？": "In that sense, I suppose I still love her.\"<br/>\r\n  How could he feel that way?",
    "<br/>\r\n  　わたしはそう訊きたかったが、街灯に照らされた叔父の小さな背中は、なんだかとってもさみしそうで、もうそれ以上何も言えなかった。": "<br/>\r\n  I wanted to ask, but my uncle's small back, illuminated by the streetlight, looked so lonely that I couldn't say anything more.",
    "<br/>\r\n  <br/>\r\n  　その夜、わたしはなぜだか寝付くことができなかった。": "<br/>\r\n  <br/>\r\n  That night, for some reason, I couldn't fall asleep.",
    "気持ちが妙に<ruby><rb>昂</rb><rt>たか</rt></ruby>ぶって、夜中になってもそわそわ落ち着かない。": "My feelings were strangely heightened, and I felt restless and uneasy even late into the night.",
    "<br/>\r\n  　そうやって長い間、布団の中で格闘していると、いろんな思いが頭の中を交錯し、パンパンに膨れ上がってしまった。": "<br/>\r\n  I lay in bed for a long time, wrestling with my thoughts as they tangled together and grew until my head felt like it would burst.",
    "この先の自分のことや、過去の苦い思い出なんかがぐるぐると頭の中を占拠してしまって苦しい。": "Thoughts of my future and bitter memories from my past circled endlessly, making it hard to breathe.",
    "<br/>\r\n  　これはまずい。": "<br/>\r\n  This is no good.",
    "わたしはがばりと起き上がった。": "I sat up abruptly.",
    "何もしなければ、どんどん苦しくなって窒息してしまう。": "If I didn't do something, the feeling would only worsen until I choked.",
    "テレビでも観ようかとも思ったけれど、そのためには前に積まれた本どもをまた片付けなければならない。": "I thought about watching TV, but that would mean clearing away the piles of books in front of me again.",
    "それに夜中の三時じゃどのみち何もやってないだろう。": "Besides, it was three in the morning; nothing would be on anyway.",
    "<br/>\r\n  　本でもあればなあ、とわたしは闇をぼんやりと見つめたまま思った。": "<br/>\r\n  If only I had a book, I thought, staring vacantly into the darkness.",
    "そうすれば、時間をやり過ごせるのに。": "I could pass the time that way.",
    "<br/>\r\n  　そこで、「あ」と声が出た。": "<br/>\r\n  Then, a realization hit me.",
    "よく考えたら、ここは本屋じゃないか。": "When I really thought about it, I was in a bookstore.",
    "本なんて腐るほどある。": "There were books everywhere.",
    "いままで敵対心しか抱いていなかったから、彼らの本来の役割をすっかり忘れてしまっていた。": "I'd been so hostile toward them that I'd completely forgotten what they were actually for.",
    "<br/>\r\n  　わたしは明かりをつけると、さっそく何か面白そうな本はないかとあたりを物色しはじめた。": "<br/>\r\n  I turned on the light and immediately began scouring the room for something interesting to read.",
    "でも、どれが面白いかなんてまるっきり見当もつかない。": "But I had absolutely no idea what might be good.",
    "どれもみな同じ、古臭い本なだけ。": "They all just looked like the same old, musty books to me.",
    "叔父ならきっとこの中から、ほいほいといくらでも自分の好きな作品を見つけられるのだろうけど。": "I'm sure my uncle could have plucked his favorites out of here one after another without a second thought.",
    "<br/>\r\n  　仕方なしに、山と成した文庫本の前に立って、目をつむった。": "<br/>\r\n  Reluctantly, I stood before the mountain of paperbacks and closed my eyes.",
    "そのまま手を伸ばし、最初に手に触れたものを「えいや」と引き抜いた。": "I reached out and, with a silent prayer, pulled out the first one I touched.",
    "それは『<ruby><rb>或</rb><rt>あ</rt></ruby>る少女の死まで』という作品だった。": "It was a book called 'Until the Death of a Certain Girl.'",
    "作者は室生犀星。": "The author was Muro Saisei.",
    "高校の現国の時間に名前だけは聞いたことがある人だ。": "It was a name I remembered hearing once in high school Japanese class.",
    "<br/>\r\n  　枕もとのランプだけの薄暗い部屋で、布団にもぐったまま、わたしは特にこれといった感慨もなくそれを読み始めた。": "<br/>\r\n  In the dim light of the bedside lamp, I crawled back under the covers and began to read, not expecting much.",
    "きっと退屈ですぐに寝てしまうだろうと思っていた。": "I figured I'd get bored and fall asleep in no time.",
    "<br/>\r\n  　ところが、どうしたことだろう。": "<br/>\r\n  But then, something unexpected happened.",
    "一時間後には、わたしはその本にすっかり夢中になってしまっていた。": "An hour later, I was completely absorbed in the story.",
    "文章としては、むずかしい言葉遣いのところもあったが、内容は普遍的な人間の心理がテーマになっていて、それがわたしの心にもすんなりと染みこんできた。": "The language was a bit difficult in places, but the themes of universal human emotions resonated deeply with me.",
    "<br/>\r\n  　物語は主人公が金沢で過ごした少年時代から、詩人になるという夢を持って上京し、根津で生活をはじめたころのことを中心に書いてあった。": "The story followed the protagonist from his childhood in Kanazawa to his move to Tokyo with dreams of becoming a poet, and his life in Nezu.",
    "そこに、腹違いの姉や、友人の恋人といった女性への思慕がからむ。": "Intertwined were his affections for women like his half-sister and his friend's lover.",
    "タイトルの「或る少女」というのも、上京後、仕事もないまま貧困の中で<ruby><rb>喘</rb><rt>あえ</rt></ruby>いでいた主人公が、ふとしたきっかけで知り合う少女のことだった。": "The 'certain girl' from the title was someone the protagonist met by chance while struggling in poverty and unemployment after coming to the city.",
    "その少女との交流により、彼の傷だらけの心がほんの一時ではあるものの、癒されていくのだ。": "Through his interactions with her, his wounded heart found a brief moment of healing.",
    "<br/>\r\n  　そうした作中でわたしが最も心引かれたのは、複雑な環境で育ち、鬱屈とした青春時代を過ごす主人公を描きながらも、どこか静かな優しさに作品全体が包まれているところだった。": "<br/>\r\n  What drew me in most was how the entire work was enveloped in a quiet kindness, even as it depicted a protagonist who grew up in a complex environment and spent his youth in frustration.",
    "その言葉では表せない穏やかな感情が、じんわりと胸に迫ってくる。": "That indescribable, gentle emotion slowly filled my chest.",
    "そう、それは強いていうならば、作者の人生への確固たる愛情からなるものに違いなかった。": "If I had to put it into words, it surely came from the author's steadfast love for life itself.",
    "<br/>\r\n  　気がつけば、もう夜が白々と明けはじめていた。": "<br/>\r\n  Before I knew it, the sky was beginning to turn pale with dawn.",
    "<br/>\r\n  　それでも、わたしは<ruby><rb>頁</rb><rt>ページ</rt></ruby>をめくり続けた。": "<br/>\r\n  But even then, I kept turning the pages.",
    "<br/>\r\n  <br/>\r\n  　翌日、サトル叔父さんがやってくると、興奮冷めやらぬ気分で彼を迎えた。": "<br/>\r\n  <br/>\r\n  The next day, when Uncle Satoru arrived, I greeted him with lingering excitement.",
    "いつもならろくに挨拶さえしないわたしが飛んできたので、叔父は目を丸くする。": "My uncle's eyes widened when I ran up to him, since I usually barely even bothered to say hello.",
    "<br/>\r\n  「この本、面白かった」とわたしは『或る少女の死まで』を手に言った。": "<br/>\r\n  \"This book was wonderful,\" I said, holding up 'Until the Death of a Certain Girl.'",
    "<br/>\r\n  　すると、どうだ。": "<br/>\r\n  And then, something remarkable happened.",
    "叔父の顔が途端にパアッと明るくなった。": "My uncle's face instantly lit up.",
    "まるで素敵な誕生日プレゼントをもらった子どもみたいに。": "He looked just like a child who had received a wonderful birthday present.",
    "<br/>\r\n  「そうだろ、そうだろ？」": "<br/>\r\n  \"Right? Isn't it?\"",
    "<br/>\r\n  　叔父は、自分のことのように興奮して言う。": "<br/>\r\n  My uncle spoke with as much excitement as if it were his own discovery.",
    "<br/>\r\n  「うん、すっごくよかった。": "<br/>\r\n  \"Yeah, it was really good.",
    "なんていうか、ぐっときた」うまい言葉がでてこない自分がもどかしかった。": "How should I put it... it really touched me.\" I felt frustrated that I couldn't find the right words.",
    "「ぐっと」なんて、わたしの心の複雑な動きの説明になど、ちっともなっていない。": "Saying it 'touched me' didn't even begin to describe the complex shift in my heart.",
    "<br/>\r\n  「いやあ、うれしいな、貴子ちゃんがそう言ってくれて。": "<br/>\r\n  \"Wow, I'm so happy to hear you say that, Takako.",
    "しかも、いきなり室生犀星とはまた渋いところを突くなあ」<br/>\r\n  　叔父が本当にうれしそうにしているので、わたしまでなんだか釣られてうれしくなってしまう。": "And starting off with Muro Saisei—that's a pretty sophisticated choice!\"<br/>\r\n  He looked so genuinely pleased that I couldn't help but feel happy too.",
    "<br/>\r\n  　わたしたちはそうして、ひとしきりその本について語りあった。": "<br/>\r\n  We spent some time talking about the book together.",
    "いままでまったく接点のないように思えた人と、ふと一つのことで結びつけることの喜び。": "There's a certain joy in suddenly finding a connection over a single thing with someone you thought you had nothing in common with.",
    "それはたとえ相手が叔父のような人でも、いや叔父ような人だからこそ、とても心弾むものだった。": "Even if that person was someone like my uncle—or perhaps precisely because it was him—it felt incredibly uplifting.",
    "<br/>\r\n  <br/>\r\n  　思わぬことが、自分が知らなかった扉を開くということもある。": "<br/>\r\n  <br/>\r\n  Sometimes, the most unexpected things can open doors you never knew existed.",
    "そのときのわたしの気持ちがまさにそれだった。": "That's exactly how I felt in that moment.",
    "<br/>\r\n  　そう、そのことがきっかけとなり、わたしはどんどん本を読みまくるようになったのだ。": "<br/>\r\n  Yes, that was the catalyst that set me off on a reading frenzy.",
    "いままでずっと心の奥で眠っていた読書欲が、ポン！": "It was as if the desire to read, which had been dormant deep inside me all this time, suddenly went *pop!*",
    "と音を立てて<ruby><rb>弾</rb><rt>はじ</rt></ruby>けて飛び出て来たみたいな気分だった。": "And burst out into the open.",
    "<br/>\r\n  　わたしは味わうようにゆっくり一冊一冊を読んでいった。": "<br/>\r\n  I took my time with each book, savoring them as I read.",
    "時間はいくらでもあったし、いくら読んでも本がなくなる心配もなかった。": "I had all the time in the world, and there was no danger of ever running out of things to read.",
    "<br/>\r\n  　永井荷風、谷崎潤一郎、太宰治、佐藤春夫、芥川龍之介、宇野浩二……。": "<br/>\r\n  Nagai Kafu, Tanizaki Junichiro, Dazai Osamu, Sato Haruo, Akutagawa Ryunosuke, Uno Koji...",
    "名前は知っているけどちゃんと読んだことのない人、名前すら知らなかった人、とにかく面白そうだと思ったものは全部手にとって<ruby><rb>貪</rb><rt>どん</rt></ruby><ruby><rb>欲</rb><rt>よく</rt></ruby>に読んだ。": "Authors I'd heard of but never really read, and authors I'd never even heard of—I greedily picked up everything that looked remotely interesting.",
    "それでも読みたいものは次から次へと見つかる。": "Even then, I kept finding more and more things I wanted to read.",
    "<br/>\r\n  　こんな素晴らしい体験があるということを、それまでぜんぜん知らなかった。": "<br/>\r\n  I'd had no idea that such a wonderful experience existed until then.",
    "なんだかいままで人生を損してきたような気持ちにさえなる。": "It made me feel like I'd been missing out on something vital my whole life.",
    "<br/>\r\n  　わたしは以前のように惰眠をむさぼることをもうやめにした。": "<br/>\r\n  I gave up my habit of sleeping my days away like I used to.",
    "もうその必要も感じなかった。": "I didn't feel the need for it anymore.",
    "眠りの中に逃げ込む代わりに、叔父と店番を交代すると、自分の部屋か喫茶店で本を読んだ。": "Instead of escaping into sleep, I would take over the shop for my uncle and spend my time reading, either in my room or at a nearby cafe.",
    "<br/>\r\n  　古本の中には、わたしの思いもしないたくさんの歴史がつまっていた。": "<br/>\r\n  The old books were filled with so much history that I'd never even considered.",
    "それは、決して本の中身に関してのことだけではない。": "And I don't just mean what was written inside them.",
    "一冊ごとに、長い年月を経た<ruby><rb>痕</rb><rt>こん</rt></ruby><ruby><rb>跡</rb><rt>せき</rt></ruby>をわたしはいくつも発見した。": "With each volume, I discovered countless traces of the long years that had passed.",
    "<br/>\r\n  　たとえば、梶井基次郎の『ある心の風景』の、ある頁ではこんな箇所に出くわした。": "<br/>\r\n  For example, on one page of Kajii Motojiro's 'A Landscape of the Heart,' I came across this passage:",
    "<br/>\r\n  <br/>\r\n  　<span class=\"u\">視ること、それはもうなにかなのだ。": "<br/>\r\n  <br/>\r\n  <span class=\"u\">\"To see something, that in itself is already something.",
    "自分の魂の一部分或いは全部がそれに乗り移ることなのだ</span><br/>\r\n  <br/>\r\n  　こんな具合に、かつてその作品を読み感銘を受けた人が、ペンで横に線を引いているのだ。": "It means that a part of your soul, or perhaps all of it, has been transferred into it.\"</span><br/>\r\n  <br/>\r\n  Someone who had been moved by the work in the past had drawn a line next to it with a pen.",
    "自分も同じくその箇所に感銘を受けたから、知らない誰かと心が通じたようでうれしくなった。": "Since I was moved by the same passage, it made me happy to feel like my heart had connected with some stranger.",
    "<br/>\r\n  　ほかにも、押し花の<ruby><rb>栞</rb><rt>しおり</rt></ruby>が入っているのを発見することもあった。": "<br/>\r\n  Other times, I would find a bookmark made of a pressed flower.",
    "そんなときわたしは、もうとっくに薄れてしまったその花の匂いを<ruby><rb>嗅</rb><rt>か</rt></ruby>ぎ、これは一体どんな人が、どんな時代に、どんな想いで、ここに挟んだのだろうなどと思いを<ruby><rb>馳</rb><rt>は</rt></ruby>せた。": "In those moments, I would try to catch the scent of the flower that had long since faded, and wonder about the person who had tucked it there—what kind of person they were, what era they lived in, and what they were thinking.",
    "<br/>\r\n  　そうした時を越えた出会いは、古本でしか決して味わえないものだった。": "<br/>\r\n  Those kinds of encounters that transcended time were something you could only experience with old books.",
    "すると、それらを扱う森崎書店という古書店へも、次第に愛情を覚えるようになった。": "And so, I gradually began to feel a certain affection for Morisaki Bookshop, the place that handled them.",
    "その静かに時が流れる小さな空間に、こうして身を置いていられることが、とても貴重なことのように思えてくる。": "Being able to spend my time in that small space where time seemed to flow so quietly began to feel like something truly precious.",
    "おかげで店の作家たちにもずいぶん詳しくなり、常連さんたちともいつの間にやらすっかり<ruby><rb>馴</rb><rt>な</rt></ruby><ruby><rb>染</rb><rt>じ</rt></ruby>みになった。": "As a result, I became quite familiar with the authors in the shop, and before I knew it, I was on friendly terms with the regular customers as well.",
    "サブさんはわたしが以前と一味違うのに気が付くと、「お、貴子ちゃん、やるじゃない」とちょっぴり見直してくれた。": "When Sabu-san noticed that I seemed a bit different than before, he gave me a little nod of approval, saying, \"Oh, Takako-chan, not bad at all.\"",
    "<br/>\r\n  　そしてもう一つ、街の散策というのも、わたしの新しい習慣となった。": "<br/>\r\n  Another new habit I picked up was taking walks around the neighborhood.",
    "<br/>\r\n  　ちょうどそのころはすっかり涼しくなり、歩き回るには持ってこいの季節だった。": "<br/>\r\n  It had just started to get cooler, making it the perfect season for exploring.",
    "街路樹の葉が日増しに黄色くなる様子は、自分の心のゆっくりとした変化と対応しているようで、なんだかぐすぐったかった。": "Watching the leaves on the trees turn yellow day by day felt like it mirrored the slow change in my own heart, which was a strange and somewhat ticklish sensation.",
    "<br/>\r\n  　歩きながら、はじめて神保町に来たときとはまったく違う気持ちで、わたしは街を眺めた。": "<br/>\r\n  As I walked, I looked at the neighborhood with completely different feelings than when I'd first arrived in Jinbocho.",
    "すると街全体が冒険の場に思えてきて、胸がわくわくした。": "Suddenly, the whole area felt like a playground for adventure, and my heart fluttered with excitement.",
    "なにせ下町情緒あふれるこの一角には、古本屋、喫茶店、異国風のバーなどふらりと立ち寄ってみたくなる店が、大通りや裏路地にたくさんあるのだ。": "After all, this corner of the city, with its old-town atmosphere, was packed with used bookstores, cafes, and exotic-looking bars that made me want to just drop in, tucked away on main streets and in back alleys alike.",
    "それでいて、街全体は独特の穏やかさに包まれ、わたしが一番苦手とする<ruby><rb>猥</rb><rt>わい</rt></ruby><ruby><rb>雑</rb><rt>ざつ</rt></ruby>な雰囲気がどこにもない。": "And through it all, the entire neighborhood was wrapped in a unique sense of calm, without a trace of the chaotic, cluttered atmosphere that I usually disliked so much.",
    "<br/>\r\n  　書店と一口に言っても一軒一軒まったく別のカラーを持っているということにも、そこでようやく気が付いた。": "<br/>\r\n  I also finally realized that even though they were all called bookstores, each one had its own distinct character.",
    "<br/>\r\n  　小説だけでも外国文学や時代小説など数多くの専門店に分かれているし、映画雑誌や児童書、江戸期の和本を扱う店まである。": "<br/>\r\n  There were specialty shops for everything from foreign literature to historical novels, and even places that dealt in movie magazines, children's books, or Japanese volumes from the Edo period.",
    "店主も祖父のような頑固オヤジ風の人もいれば、まだ年若くて物腰も柔和な人などさまざまだ。": "The shop owners were just as varied—some were stubborn old men like my grandfather, while others were young and had a gentle, soft-spoken manner.",
    "ふらりと立ち寄った街の案内所で教えてもらったところによれば、書店だけで実に百七十以上ものお店があるという。": "According to what I learned at a local information center I happened to drop by, there were actually over a hundred and seventy bookstores in the area.",
    "なるほど、ここは叔父の言っていたように、世界一の書店街だった。": "I saw then that it truly was the world's greatest bookstore district, just as my uncle had said.",
    "<br/>\r\n  　やがて歩き疲れれば、喫茶店で一休みした。": "<br/>\r\n  When I eventually grew tired from walking, I would take a break in a cafe.",
    "<br/>\r\n  　温かいコーヒーは肌寒くなってきた季節にはぴったりで、散策の終わりに飲むと心が<ruby><rb>芯</rb><rt>しん</rt></ruby>からほっとした。": "<br/>\r\n  A hot cup of coffee was just right for the chilly season, and drinking it at the end of a walk made me feel warm and relaxed to the core.",
    "<br/>\r\n  <br/>\r\n  　秋の深まる日々を、わたしはそうして過ごした。": "<br/>\r\n  <br/>\r\n  I spent my days like that as autumn deepened.",
    "<br/>\r\n  　新しい日課が、わたしの気持ちを引っ張り上げてくれたことは疑いないことだった。": "<br/>\r\n  There was no doubt that my new routine was lifting my spirits.",
    "心の中で長いことわだかまっていたものが、するするとほどけていくような、そんな気持ちがした。": "It felt as if the things that had been weighing on my heart for so long were slowly beginning to unravel.",
    "<br/>\r\n  　ちょうどそれと呼応するように、この街に知り合いも増えてきた。": "<br/>\r\n  And as if in response, I began to make more acquaintances in the neighborhood.",
    "行きつけの喫茶店である〈すぼうる〉では、マスターやスタッフさんともずいぶん親しくなり、中でもウェイトレスのトモちゃんとはすっかり仲良しになった。": "At 'Suboru,' the cafe I frequented, I became quite close with the master and the staff, and I especially hit it off with a waitress named Tomo-chan.",
    "<br/>\r\n  　トモちゃんは国文科の大学院の一年生で、空いた時間に〈すぼうる〉でアルバイトしていた。": "<br/>\r\n  Tomo-chan was a first-year graduate student in the Japanese Literature department, and she worked part-time at 'Suboru' in her spare time.",
    "森崎書店にも、ときどきお客さんとしてやって来た。": "She would also drop by Morisaki Bookshop as a customer from time to time.",
    "年はわたしの二つ下。": "She was two years younger than me.",
    "普段は大人しく、おっとりしているように見えるのだが、その見かけとは裏腹に、熱い情熱を心の奥に彼女は秘めていた。": "She usually seemed quiet and mild-mannered, but beneath that exterior, she hid a deep, burning passion.",
    "特に国文科の学生だけあって、作家たちへの愛情は並々ならぬものがあった。": "As a student of Japanese literature, her love for authors was truly extraordinary.",
    "彼女のそうした豊かな人間性は、わたしにはとても好ましく思えた。": "I found her rich personality incredibly appealing.",
    "<br/>\r\n  　そのうち、トモちゃんは用事がなくても、バイト帰りに書店を訪ねてきてくれるようになり、二人で本に囲まれた二階で一緒にお茶を飲んだりした。": "<br/>\r\n  Eventually, Tomo-chan started visiting the bookstore after work even when she didn't have any business there, and we'd have tea together on the second floor, surrounded by books.",
    "<br/>\r\n  「わあ、ここ、夢のような環境ですね」<br/>\r\n  　トモちゃんははじめて部屋にやってきたとき、顔を輝かせて言った。": "<br/>\r\n  \"Wow, this is like a dream setting!\" Tomo-chan said, her face lighting up when she first visited my room.",
    "<br/>\r\n  「え、そうかな？": "<br/>\r\n  \"Oh, you think so?",
    "さすがに狭いよ。": "It's pretty cramped, honestly.",
    "ガスコンロもひとつしかないし」<br/>\r\n  　利便性の面ではとても褒められたものではないので、わたしは生活する者として率直な意見を言った。": "I've only got one gas burner.\"<br/>\r\n  I gave her my honest opinion as someone who actually lived there, since it wasn't exactly a model of convenience.",
    "<br/>\r\n  「そこがまたいいんじゃないですか」とトモちゃんは、わかってないなあという顔になる。": "\"But that's exactly what's so great about it!\" Tomo-chan said, looking at me as if I just didn't get it.",
    "「余計なものはひとつとしてなく、手を伸ばせば本がそこにある。": "\"There's not a single unnecessary thing here, and you can reach out and touch a book from anywhere.",
    "最高じゃないですか」<br/>\r\n  「そう、なのかな」<br/>\r\n  「そうです」<br/>\r\n  　トモちゃんはわたしの前にぐっと顔を寄せ、瞳をきらきらさせて言った。": "Isn't it perfect?\"<br/>\r\n  \"I guess so...\"<br/>\r\n  \"It is!\"<br/>\r\n  Tomo-chan leaned in close, her eyes sparkling with excitement.",
    "<br/>\r\n  　わたしは部屋をぐるりと見回してみた。": "<br/>\r\n  I took a good look around the room.",
    "彼女に興奮気味にそう言われると、いままで味気なく思っていた部屋が、とても素敵な空間のように思えてくるから不思議だった。": "It was strange how, after hearing her talk about it with such enthusiasm, the room that I'd found so dull until then suddenly started to look like a truly wonderful place.",
    "<br/>\r\n  　トモちゃんのもっと部屋を素敵にしようという発案により、わたしたちは四つ角のところにある花屋さんでコスモスを買い、花瓶に<ruby><rb>活</rb><rt>い</rt></ruby>けてちゃぶ台に飾った。": "<br/>\r\n  Following Tomo-chan's suggestion to make the room even more charming, we bought some cosmos at a flower shop on the corner, arranged them in a vase, and set them on the low table.",
    "すると、部屋は以前よりもずっと明るくなった気がした。": "Immediately, the room felt so much brighter than before.",
    "それ以来、わたしはいつも季節の花をそこに飾るようにした。": "From then on, I made sure to always have seasonal flowers on display there.",
    "<br/>\r\n  　そうしてすっかり仲良しになったころ、お茶を飲みながら、わたしは彼女にふとこう<ruby><rb>訊</rb><rt>たず</rt></ruby>ねてみた。": "<br/>\r\n  Once we'd become truly close, I happened to ask her one day while we were having tea:",
    "<br/>\r\n  「トモちゃんは、どうしてそんなに本を好きになったの？」": "<br/>\r\n  \"Tomo-chan, how did you become such a book lover?\"",
    "<br/>\r\n  　すると彼女は、いつものやわらかな声でこんなことを言った。": "<br/>\r\n  She replied in her usual soft voice.",
    "<br/>\r\n  「うーんと、そうですね。": "<br/>\r\n  \"Well, let's see.",
    "わたしは中学のころ、他人に自分の意見を言うのが怖くって、ひどく無口な子だったんです。": "When I was in middle school, I was a terribly quiet kid because I was scared to tell people what I really thought.",
    "そのくせ心の中ではすごく嫌な感情がどろどろうずまいていて、そういう自分がひどく醜く思えてしまって……。": "But at the same time, I had all these nasty feelings swirling around inside me, and I felt so ugly for having them...",
    "そんなとき、姉が持ってた太宰治の『女生徒』を読んだのがはじまりですね。": "That's when I picked up my sister's copy of Dazai Osamu's 'Schoolgirl.' That was the beginning of it all.",
    "で、いまではけっこうどっぷりはまっちゃってます」<br/>\r\n  「へえ。": "And now, I'm completely hooked.\"<br/>\r\n  \"Wow.",
    "きっと読書家の人は、そんなふうに人生のどこかで本と出会って、忘れられない体験をしてるんだねえ」<br/>\r\n  　わたしは感心して言った。": "I guess all big readers must have had a moment like that somewhere in their lives where they encountered a book and had an experience they'd never forget.\"<br/>\r\n  I was truly impressed.",
    "<br/>\r\n  「二人とも、これからもいっぱい素敵な本と出会えたらいいですね」<br/>\r\n  　にっこりと笑うトモちゃんに、わたしも「うん、そうだね」と力いっぱい頷いた。": "<br/>\r\n  \"I hope we both get to encounter lots more wonderful books from now on,\" Tomo-chan said with a smile, and I nodded back enthusiastically, \"Yeah, I hope so too.\"",
    "<br/>\r\n  　そしてそのころ、彼女つながりでは、こんなことまであった。": "<br/>\r\n  And around that same time, something else happened, thanks to my connection with her.",
    "<br/>\r\n  　ある昼下がり、わたしがひとりで店番をしていると、〈すぼうる〉で働く高野君がふらりとやってきた。": "<br/>\r\n  One afternoon, while I was minding the shop alone, Takano-kun from 'Suboru' happened to drop by.",
    "<ruby><rb>厨</rb><rt>ちゆう</rt></ruby><ruby><rb>房</rb><rt>ぼう</rt></ruby>で働く彼とはそんなに話す機会はなかったが、そのひょろりとした姿はお店の中でもやたらと目を引くものだった。": "Working in the kitchen, he didn't have many chances to talk, but his tall, thin figure was always quite noticeable in the cafe.",
    "<br/>\r\n  　わたしはすぐに彼に気が付き、「こんにちは」と声をかけた。": "<br/>\r\n  I recognized him immediately and said hello.",
    "<br/>\r\n  　高野君は「どうも」とお辞儀すると、妙に落ち着かない様子で店内をきょろきょろしている。": "<br/>\r\n  Takano-kun gave me a polite nod and then started glancing around the shop, looking strangely restless.",
    "<br/>\r\n  　変な子だなあと思いながら、「何か捜してるの？」": "<br/>\r\n  I thought he was acting a bit odd, so I asked, \"Are you looking for something?\"",
    "とさらに声をかけると、彼は「いや、あの、いや……」としどろもどろになってしまった。": "When I pressed him further, he just stammered, \"No, well, um, no...\"",
    "<br/>\r\n  　なんなのだろう、なんか顔も赤いし。": "<br/>\r\n  What was going on? His face was even turning a bit red.",
    "まるで好きな子を前にした男の子みたいではないか。": "He looked exactly like a boy standing in front of the girl he likes.",
    "わたしはそこで、はっとした。": "Then it hit me.",
    "ひょっとして、彼はわたしに気があるんじゃないだろうか。": "Wait, could he have a thing for me?",
    "そういえば、叔父に「デートしてあげてよ」と言われたときも、異常なまでに照れまくっていた。": "Now that I thought about it, he'd been incredibly embarrassed when my uncle told him he should take me on a date.",
    "あれはつまり……。": "Could that mean...",
    "そう考えた途端、急にこっちまで緊張してきてしまった。": "As soon as the thought crossed my mind, I suddenly started to feel nervous too.",
    "<br/>\r\n  　気まずい沈黙が、店内にしばらく流れた。": "<br/>\r\n  An awkward silence hung in the shop for a while.",
    "どんどん空気が濃くなっていくようで、息が苦しい。": "The air felt like it was growing thicker, making it hard to breathe.",
    "<br/>\r\n  　その密度に、これ以上耐え切れなくなったわたしが口を開こうとしたのと同時に、彼が「あの！」": "<br/>\r\n  Just as I was about to open my mouth, unable to stand the tension any longer, he suddenly blurted out, \"Um!\"",
    "と大きな声で言った。": "In a loud voice.",
    "<br/>\r\n  　わたしは思わず身構えた。": "<br/>\r\n  I braced myself, almost instinctively.",
    "そのときには、もうすっかり愛を告白されるものだと思い込み、どう<ruby><rb>婉</rb><rt>えん</rt></ruby><ruby><rb>曲</rb><rt>きよく</rt></ruby>に断ればいいのかと頭をぐるぐるめぐらしていた。": "By then, I was completely convinced he was about to confess his love, and I was already frantically trying to figure out the gentlest way to turn him down.",
    "<br/>\r\n  　だが、彼が次に発した言葉は、わたしの予想とはぜんぜん違うものだった。": "<br/>\r\n  But what he said next was completely different from what I'd expected.",
    "<br/>\r\n  「相原さんって、よくここに来ますよね？」": "<br/>\r\n  \"Aihara-san comes here pretty often, doesn't she?\"",
    "<br/>\r\n  　高野君は顔を真っ赤にしてそう言った。": "<br/>\r\n  Takano-kun said, his face flush with red.",
    "<br/>\r\n  「相原さんって……トモちゃんのこと？」": "<br/>\r\n  \"Aihara-san... you mean Tomo-chan?\"",
    "<br/>\r\n  「そうです」<br/>\r\n  「うん、よく喫茶店のお昼休みなんかにも顔見せに来てくれるけど？」": "<br/>\r\n  \"Yes.\"<br/>\r\n  \"Yeah, she drops by to see me during her lunch breaks at the cafe pretty often. Why?\"",
    "<br/>\r\n  「彼女と、どんなこと話すんですか？」": "<br/>\r\n  \"What kind of things do you talk about with her?\"",
    "<br/>\r\n  　急速に、わたしの中の熱が冷めていった。": "<br/>\r\n  Immediately, any excitement I'd felt vanished.",
    "さっきの緊張、返せ、と心の中で思わずつぶやいた。": "Give me back that nervousness from a second ago, I grumbled to myself.",
    "<br/>\r\n  「へえ。": "<br/>\r\n  \"Oh.",
    "トモちゃんのこと、好きなんだ？」": "So, you like Tomo-chan, do you?\"",
    "<br/>\r\n  　わたしは腹いせに、意地悪く訊ねてやった。": "<br/>\r\n  I decided to be a little mean and just ask him directly, as a bit of payback.",
    "<br/>\r\n  「いや、そういうわけじゃないけど……」<br/>\r\n  「いいのいいの。": "<br/>\r\n  \"No, it's not like that, exactly...\"<br/>\r\n  \"It's fine, it's fine.",
    "確かにトモちゃん、とっても可愛いもんね。": "Tomo-chan is definitely very cute.",
    "でも、彼女のことは一緒の店で働いてる高野君の方がよく知ってるでしょ？」": "But you work at the same place as her, so you must know her better than I do, right?\"",
    "<br/>\r\n  「いや、俺、キッチンだし、彼女はホールだし。": "<br/>\r\n  \"No, I'm in the kitchen and she's out on the floor.",
    "それに俺、口下手だから……」<br/>\r\n  「ふうん。": "Besides, I'm not very good with words...\"<br/>\r\n  \"Hmm.",
    "見かけどおり、ほんとにシャイなのねえ」<br/>\r\n  「恋人とかいるんですかね？」": "So you really are as shy as you look.\"<br/>\r\n  \"Do you think... she has a boyfriend?\"",
    "<br/>\r\n  　高野君は、この世の一大事とでもいうような口調でわたしに訊ねた。": "<br/>\r\n  Takano-kun asked me with an intensity that made it sound like the most important question in the world.",
    "<br/>\r\n  「さあ？": "<br/>\r\n  \"Who knows?",
    "そういえば、訊いたことなかったな。": "Now that you mention it, I've never asked her.",
    "でも、トモちゃん、可愛いし、すごく感じのよい子だからなあ。": "But since she's so cute and has such a great personality...",
    "いてもぜんぜんおかしくないと思うけど」<br/>\r\n  「じゃあ、今度さりげなく訊いてみてもらえませんか？」": "It wouldn't surprise me at all if she did.\"<br/>\r\n  \"Well, could you maybe ask her for me next time, without being too obvious about it?\"",
    "<br/>\r\n  「なんでわたしがそんなことを？": "<br/>\r\n  \"Why should I do that?",
    "それくらい自分で訊けばいいじゃない」<br/>\r\n  「貴子さんなら、仲良しだから自然に訊けるでしょ？": "You can just ask her yourself, can't you?\"<br/>\r\n  \"But you're such good friends, so you could ask her naturally, right?",
    "それに俺、いままで女の子に自分から声かけたことなくって……」<br/>\r\n  「いま、かけてるよ……」わたしは<ruby><rb>愕</rb><rt>がく</rt></ruby><ruby><rb>然</rb><rt>ぜん</rt></ruby>として言った。": "Besides, I've never actually spoken to a girl first in my entire life...\"<br/>\r\n  \"You're talking to one right now...\" I said, completely taken aback.",
    "わたしは女じゃないってことなのか。": "Did he not consider me a girl?",
    "しかし、彼はまったく気付く様子がない。": "But he didn't seem to notice my reaction at all.",
    "<br/>\r\n  「ただとは言いません。": "<br/>\r\n  \"I won't ask for nothing.",
    "協力してくれたら、店に来たときのコーヒー代、俺がこれから全部おごります」<br/>\r\n  　彼のその一言に、わたしはそれまでのことすべてを帳消しにして、顔を輝かせた。": "If you help me out, I'll pay for all your coffee whenever you come to the cafe from now on.\"<br/>\r\n  With those words, I immediately forgot any annoyance I'd felt and my face lit up.",
    "<br/>\r\n  「ほんとうに？": "<br/>\r\n  \"Really?",
    "それなら毎日行くよ？」": "In that case, I'll go every day!\"",
    "<br/>\r\n  「いや、さすがに毎日はちょっと……」<br/>\r\n  「なにケチくさいこと言ってるの？": "<br/>\r\n  \"Wait, maybe not every day...\"<br/>\r\n  \"Don't be so stingy!",
    "たったコーヒー一杯で憧れの彼女とお近づきになれるんだよ？」": "For just the price of a cup of coffee, you could get closer to the girl of your dreams!\"",
    "<br/>\r\n  「はあ……」と高野君は渋々納得したように頷く。": "<br/>\r\n  \"I guess...\" Takano-kun said, nodding reluctantly.",
    "「でも彼女には、このことは絶対言わないって約束してください」<br/>\r\n  「わかってるって」わたしは自分の胸を、どんと<ruby><rb>叩</rb><rt>たた</rt></ruby>いて言った。": "\"But you have to promise not to tell her about this.\"<br/>\r\n  \"I know, I know,\" I said, giving my chest a reassuring pat.",
    "<br/>\r\n  　こうして、わたしと高野君は密約を交わした。": "<br/>\r\n  And so, Takano-kun and I entered into a secret pact.",
    "なんでも高野君は、もう半年近くもトモちゃんにひそかに想いを寄せているらしい。": "Apparently, he'd been harboring feelings for Tomo-chan for nearly six months.",
    "でも、その間、挨拶以上の会話をしたことがなく、ずっと陰から素敵だなあと思っていただけなのだそうだ。": "But in all that time, they'd never spoken beyond basic greetings, and he'd just been admiring her from afar.",
    "暗いといえば暗いが、まあ純情ともいえる。": "It was a bit gloomy, in a way, but also kind of sweet and innocent.",
    "<br/>\r\n  　引き受けてしまった以上、わたしもどうせなら二人をうまくいかせたかった。": "<br/>\r\n  Since I'd agreed to it, I genuinely wanted things to work out for the two of them.",
    "トモちゃんからすれば大きなお世話だろうが、高野君は照れ屋ではあるが、なかなか真面目な好青年だ。": "Tomo-chan might have found it meddlesome, but Takano-kun was a serious, good-natured young man, despite his shyness.",
    "チャンスくらいあげても、罰は当たらない気がする。": "I figured there was no harm in giving him a little help.",
    "<br/>\r\n  　そこで、わたしはコーヒーのため、ではなく、若い二人のために尽力した。": "<br/>\r\n  So, I did my best—not just for the coffee, but for the sake of the two young people.",
    "まずは、トモちゃんからそれとなくあれこれ情報を訊きだしてみた。": "First, I tried to subtly extract various bits of information from Tomo-chan.",
    "そうして知ったところによると、彼女には恋人はいま現在おらず、特に意中の人もいないらしい。": "From what I gathered, she didn't have a boyfriend at the moment, nor did she seem to have anyone special in mind.",
    "好きな色は紺青色。": "Her favorite color was deep blue.",
    "好きな動物はヤマネ。": "Her favorite animal was the dormouse.",
    "好きな街はもちろん神保町。": "And her favorite neighborhood, of course, was Jinbocho.",
    "そのうち、すっかりトモちゃん通となり、事情を知らない彼女にはちょっと気味悪がられてしまった。": "Before long, I became quite an expert on Tomo-chan, and since she didn't know what was going on, she actually started to find me a bit creepy.",
    "<br/>\r\n  　わたしは新たな情報を得ると〈すぼうる〉へと出向き、おごりのコーヒーを飲みつつ高野君にそれらを伝えた。": "<br/>\r\n  Every time I got new information, I'd head over to 'Suboru,' drink my free coffee, and pass it on to Takano-kun.",
    "「トモちゃんの好きな動物はなんとヤマネらしいよ」わたしがカウンター越しに小声で言うと、高野君も「そ、それはすごいですね」と小声で返す。": "\"Apparently Tomo-chan's favorite animal is the dormouse,\" I whispered to him across the counter, and he whispered back, \"W-wow, that's amazing.\"",
    "そのせいで意外と<ruby><rb>詮</rb><rt>せん</rt></ruby><ruby><rb>索</rb><rt>さく</rt></ruby>好きなマスターには、「あの二人はできている」とまったくのデマを常連たちに流されてしまった。": "Because of that, the master, who was surprisingly fond of prying, started spreading a completely false rumor among the regulars that the two of us were dating.",
    "<br/>\r\n  　けれど、わたしのそうした努力も二人の役にはまるで立たなかった。": "<br/>\r\n  However, all my efforts didn't seem to be doing the two of them much good.",
    "肝心の高野君がトモちゃんと話す機会をつくろうとしないので、ちっとも進展しないのだ。": "Since Takano-kun refused to make any move to talk to Tomo-chan himself, there was no progress at all.",
    "彼はトモちゃんに恋人がいないのを知っただけで勝利の<ruby><rb>雄</rb><rt>お</rt></ruby><ruby><rb>叫</rb><rt>たけ</rt></ruby>びをあげていたが、このままでは世間話をできるようになるまでにあと十年はかかるだろう。": "He was practically shouting with joy just knowing she didn't have a boyfriend, but at this rate, it would take another ten years before they were even making small talk.",
    "それでは意味がない。": "That just wasn't going to work.",
    "<br/>\r\n  　わたしはひとりで勝手にやきもきしていた。": "<br/>\r\n  I was getting restless all on my own.",
    "なんとか二人が喋れる機会をつくってはあげれぬものかと、あれこれ考えた。": "I tried to think of some way to give them an opportunity to talk.",
    "<br/>\r\n  　と、思わぬところから朗報が舞い込んできた。": "<br/>\r\n  Then, some good news arrived from an unexpected place.",
    "<br/>\r\n  　部屋で一緒に平和な気分でお茶を飲んでいたある午後、トモちゃんが古本まつりのことを教えてくれたのだ。": "<br/>\r\n  One afternoon, while we were having a peaceful tea together in my room, Tomo-chan told me about the used book festival.",
    "<br/>\r\n  「古本まつり？": "<br/>\r\n  \"A used book festival?",
    "なあにそれ？」": "What's that?\"",
    "<br/>\r\n  　わたしはきょとんとして訊ねた。": "<br/>\r\n  I asked, a bit bewildered.",
    "<br/>\r\n  「あれ、貴子さん、知らないんですか？": "<br/>\r\n  \"Wait, you didn't know about it, Takako-san?",
    "毎年秋に、このへんの古本屋さんが一斉に青空掘り出し市をやるんです。": "Every year in the fall, all the used bookstores around here hold an outdoor bargain market all at once.",
    "神保町一帯が、たくさんの人で<ruby><rb>賑</rb><rt>にぎ</rt></ruby>わってすごいんですよ」<br/>\r\n  「へえ、そうなんだ。": "The whole Jinbocho area gets incredibly crowded with people.\"<br/>\r\n  \"Oh, I see.",
    "それは楽しそうだね」<br/>\r\n  「森崎さんのところももちろん参加してますよ」": "That sounds like fun.\"<br/>\r\n  \"Morisaki Bookshop participates too, of course.\"",
    "<br/>\r\n  「ええ？": "<br/>\r\n  \"Really?",
    "そうなの？」": "We do?\"",
    "<br/>\r\n  「そりゃあ、どこのお店も参加してますもん」<br/>\r\n  　叔父ときたら、そういう肝心なことはちっとも教えてくれないから困る。": "<br/>\r\n  \"Well, every shop in the neighborhood does.\"<br/>\r\n  It's just like my uncle not to mention something so important.",
    "あとでとっちめてやろう、とわたしは心に固く誓った。": "I made a silent vow to give him a piece of my mind later.",
    "<br/>\r\n  「わたし、今年は遊びに行こうと思ってるんですけど、よかったら一緒に周りませんか？」": "<br/>\r\n  \"I was planning to go check it out this year, would you like to come along with me?\"",
    "<br/>\r\n  　そこでわたしは、ピンとひらめいた。": "<br/>\r\n  Right then, a bright idea hit me.",
    "そうだ、これを利用しない手はないではないか。": "Yes! This was the perfect opportunity.",
    "高野君にも知らせてやろう。": "I'd have to let Takano-kun know.",
    "<br/>\r\n  　わたしは「うん、行く行く」と二つ返事でオーケーした。": "<br/>\r\n  I immediately agreed, saying, \"Yeah, I'll definitely go!\"",
    "<br/>\r\n  　神田古本まつりは十月下旬から、一週間にわたって開催された。": "<br/>\r\n  The Kanda Used Book Festival was held for a week starting in late October.",
    "期間中、古本の詰まったワゴンや書棚が、フリーマーケットのように通りいっぱいに出現した。": "During that time, wagons and bookshelves overflowing with used books appeared all along the streets, like a giant flea market.",
    "<br/>\r\n  　おまつりは、驚くほどに盛況だった。": "<br/>\r\n  The festival was incredibly lively.",
    "老若男女問わず、大勢の本を愛する人たちが街にやってきた。": "Crowds of book lovers of all ages flocked to the neighborhood.",
    "年に一度の催しということもあるのだろうが、それはわたしの想像を<ruby><rb>遥</rb><rt>はる</rt></ruby>かに超えた賑わいようだった。": "Maybe it's because it's an annual event, but it was bustling far beyond anything I'd imagined.",
    "靖国通りやさくら通りは人がつくりだす熱気に包まれ、いつもはセピア色の古書店街が昼前から活気に満ちた。": "Yasukuni-dori and Sakura-dori were filled with a heat generated by the crowds, and the usually sepia-toned used bookstore district was alive with energy from early in the morning.",
    "それは、なかなか壮観な眺めだった。": "It was truly a magnificent sight.",
    "<br/>\r\n  　我らが森崎書店ももちろんおまつりに参加した。": "<br/>\r\n  Our very own Morisaki Bookshop participated in the festival too.",
    "サトル叔父さんと二人で数日かけてより分けた大量の古本を、ワゴンに乗せ店の前に出した。": "Uncle Satoru and I spent several days sorting through a huge number of old books, which we then loaded onto a wagon and set out in front of the shop.",
    "うれしいことにいつもの倍以上のお客さんがお店にやってきてくれ、中にはこのチャンスを逃すまいと、大特価品の段ボールをまるまる一箱、買っていくつわものも現れた。": "Happily, we had more than twice as many customers as usual, and some people even bought entire cardboard boxes full of bargain items, determined not to let the opportunity pass them by.",
    "<br/>\r\n  　予想していた通り、祭りごと好きの叔父は、まさに水を得た魚のように大はしゃぎだった。": "<br/>\r\n  As I'd expected, my uncle, who loved festivals, was in his element, acting just like a fish in water.",
    "子どものころから、毎年のように古本まつりには来ていたらしい。": "Apparently, he'd been coming to the used book festival almost every year since he was a child.",
    "そのため、この時期は身体が反射的にうずいてしまうとのことだった。": "He told me that his body just naturally started to itch for it around this time of year.",
    "<br/>\r\n  「これから寒くなってくると、お店に来てくれる人がぐんと減っちゃうからね。": "<br/>\r\n  \"Once it starts getting colder, the number of people coming to the shop will drop significantly.",
    "この期間にたっぷり稼いでおかなくっちゃ」と、珍しく商売人らしいことを言う叔父だったが、その言葉とは裏腹に、ちょっとでも目を離すと近辺のお店を冷やかしに行ってしまう。": "We've got to make a good profit during this period,\" my uncle said, sounding unusually like a businessman, but despite his words, he'd go off to browse the nearby shops the moment I took my eyes off him.",
    "もちろん、そのたびに叔父を連れ戻すのはわたしの役目だった。": "Of course, it was my job to drag him back every time.",
    "<br/>\r\n  　三日目の夕方、叔父の許しをもらって仕事を早めにあがると、トモちゃんとおまつり見学に出た。": "<br/>\r\n  On the evening of the third day, with my uncle's permission, I finished work early and went out to explore the festival with Tomo-chan.",
    "そして、そこに計画通り、さも偶然のように高野君が現れた。": "And then, right on cue and as if by pure coincidence, Takano-kun appeared.",
    "<br/>\r\n  　わたしと高野君は「おや、偶然ですね」「あらまあ、ほんとだわ」などと大根役者丸出しの演技しかできなかったが、根が純真なトモちゃんはちっとも気付かぬ様子だった。": "<br/>\r\n  Takano-kun and I were terrible actors, barely managing to sputter things like \"Oh, what a coincidence!\" and \"My, what a surprise!\", but Tomo-chan, being so pure-hearted, didn't seem to suspect a thing.",
    "それで、「じゃあ三人で行きましょうよ」ということになった。": "So, it was decided that the three of us would go together.",
    "<br/>\r\n  　高野君はトモちゃんを前にして、最初コチコチに固まっていた。": "<br/>\r\n  At first, Takano-kun was completely frozen in front of Tomo-chan.",
    "わたしが心配して、「ロボコップみたいだよ」とこっそり<ruby><rb>囁</rb><rt>ささや</rt></ruby>くと、高野君は「歩き方を忘れてしまいました」と声までロボットのようになって言った。": "I whispered to him in concern, \"You look like Robocop,\" and he replied in a voice that was just as robotic, \"I've forgotten how to walk.\""
}

# The target output should be a JSON object mapping source JA to target EN
output_data = {}
for ja, en in translations.items():
    output_data[ja] = en

with open(dest_path, 'w', encoding='utf-8') as f:
    json.dump(output_data, f, ensure_ascii=False, indent=2)

print(f"Saved {len(output_data)} translations to {dest_path}")
